# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '更改邮箱')], max_length=50, verbose_name='类型'),
        ),
    ]
