# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181002_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthday',
            new_name='birday',
        ),
    ]
